@startuml

Usuario <|-- Perfil
Perfil <|-- Enderecos

class Usuario {
    -- Contructors & destructors --
    - Instance()
    
    -- Public methods --
    + Nome() : string
    + Initialize() : bool
}

class Perfil {
    -- Contructors & destructors --
    - Instance()
    
    -- Public methods --
    + Initialize() : bool
}

class Enderecos {
    -- Contructors & destructors --
    - Instance()
    
    -- Public methods --
    + Initialize() : bool
}

@enduml
