@startuml
Usuario <|-- Perfil
Perfil <|-- Enderecos
Usuario "1" -- "0...*" Enderecos

class Usuario {
    -- Contructors & destructors --
    - Nome  : string
    - Idade : int
    - Email : string
    - Senha : string
    
    -- Public methods --
    + CadastrarUsuario()
    + EditarUsuario()
}

class Perfil {
    -- Contructors & destructors --
    - Instance()
    
    -- Public methods --
    + Initialize() : bool
}

class Enderecos {
    -- Contructors & destructors --
    - Instance()
    
    -- Public methods --
    + Initialize() : bool
}
@enduml
